# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rominho10
# "service" is the name of this project. This will also be added to your AWS resource names.
service: foodiary-api

provider:
  name: aws
  region: us-east-2
  runtime: nodejs22.x
  architecture: arm64

package:
  individually: true

# esbuild
build:
  esbuild:
    minify: true
    sourcemap: false

functions:
  signin:
    handler: src/signin.handler
    events:
      - httpApi:
          path: /signin
          method: POST

  signup:
    handler: src/signup.handler
    events:
      - httpApi:
          path: /signup
          method: POST